CS-2090 / CS-2094 / CS-2096 / CS-2146
GovAlta/adsp-monorepo pull request #1756
Opened 2023-06-09 22:55 UTC by jonathanweyermann

![image](https://github.com/GovAlta/adsp-monorepo/assets/11400938/a111a540-664c-412c-a4a9-66caa1981bf8)
![image](https://github.com/GovAlta/adsp-monorepo/assets/11400938/f76d74ca-336d-46d6-ad66-d92679d10756)
![image](https://github.com/GovAlta/adsp-monorepo/assets/11400938/70fd2e99-efd8-43ba-991d-fa9fbebaa5a9)

2023-06-12 18:03 UTC, rstyan requested changes

2023-06-12 18:16 UTC, jonathanweyermann commented on apps/status-service/src/app/jobs/checkEndpoint.ts
> +      waitTimeHistoryDouble.forEach((w, index) => {
ok

2023-06-12 18:16 UTC, jonathanweyermann commented on apps/status-service/src/app/jobs/checkEndpoint.ts
> +      const waitTimeHistoryDouble = await endpointStatusEntryRepository.findRecentByUrlAndApplicationId(
ok, I'll make this more clear

2023-06-12 18:17 UTC, jonathanweyermann commented on apps/status-service/src/app/jobs/checkEndpoint.ts
> +      const waitTimeHistoryDouble = await endpointStatusEntryRepository.findRecentByUrlAndApplicationId(
Its basically double the number of pings that waittime reflects

2023-06-12 18:23 UTC, jonathanweyermann commented on apps/status-service/src/app/jobs/checkEndpoint.ts
> +        if (w.ok && index === waitTimeHistoryDouble.length / 2) {
I'm intentionally ignoring them. I don't require that all pings be up or down before you have waitTime number of down pings, just that there is one last up and then waitTime number of down pings. Essentially i'm just looking for waitTime number of down pings in a row, regardless of what happens before. This switchoncount is a little different and takes into account the whole row, so the logic is a little mixed in there with that, which I guess could be confusing

2023-06-19 19:03 UTC, jonathanweyermann commented on apps/push-service/src/push/router/stream.ts
> +  eventServiceAmp: DomainEventSubscriberService;
Probably have to do this regardless

2023-06-20 14:47 UTC, rstyan approved these changes

2023-06-20 15:30 UTC, merged