feat: review page fields alignment
GovAlta/adsp-monorepo pull request #2735
Opened 2024-03-21 17:35 UTC by RamaChandiniDevarapalli

2024-03-21 21:37 UTC, thdlam requested changes
Is it possible to change some of types you are passing into to renderFormFields  with specific types instead of any.
Also write some unit test for renderFormFields.

2024-03-21 21:51 UTC, solittlework approved these changes

2024-03-21 21:51 UTC, solittlework commented on libs/jsonforms-components/src/lib/Controls/FormStepper/FormStepperControl.tsx
> +  ajv: any, // eslint-disable-line @typescript-eslint/no-explicit-any
I think we still know the ajv and requiredFiields type.

2024-03-22 12:33 UTC, rstyan requested changes

2024-03-22 12:33 UTC, rstyan commented on libs/jsonforms-components/src/lib/Controls/FormStepper/FormStepperControl.tsx
> +    function findRequired(fields: any) {
Is it really _any_?  Maybe in this case it is, but I see you are using _any_ a lot.  Please try to determine types where possible. Types are your friend.

2024-03-22 12:33 UTC, rstyan commented on libs/jsonforms-components/src/lib/Controls/FormStepper/FormStepperControl.tsx
> +
Please move this function into a separate file.  Then you function's signature woudl be something like:
```
getAllRequiredFields(fields: Array<something>, schema: JsonSchema): Array<string> { ... }
```
Then, add another file for unit tests on this function.

2024-03-22 12:33 UTC, rstyan commented on libs/jsonforms-components/src/lib/Controls/FormStepper/FormStepperControl.tsx
> +export const renderFormFields = (
Any time you see large functions like this inside a file, please try to extract it into its own, testable, reusable file.  Start thinking about the size of files - generally they should not be larger than a couple of hundred lines of code, at most.  Moving chunks of complex code into separate files makes things much easier to digest for people reviewing, and maintaining this code.  Do you know about separation of concerns?

This function looks quite complex, and should have a large number of unit tests to cover the various bits of logic.  Thats much easier to do if the function can be isolated.

2024-03-25 15:19 UTC, rstyan approved these changes
Well done, Rama!

2024-03-25 15:33 UTC, thdlam approved these changes

2024-03-25 15:42 UTC, merged