feat: loading-forms-from-form-service-namespace
GovAlta/adsp-monorepo pull request #3242
Opened 2024-08-02 18:02 UTC by RamaChandiniDevarapalli

2024-08-02 19:17 UTC, solittlework approved these changes

2024-08-02 22:12 UTC, thdlam commented on apps/tenant-management-webapp/src/app/pages/admin/services/form/definitions/definitions.tsx
> +                testId="calendar-event-load-more-btn"
@RamaChandiniDevarapalli  please update the testids in your html that has calendar in it so it doesnt break the e2e.

2024-08-02 22:13 UTC, thdlam requested changes
please fix test ids

2024-08-05 19:32 UTC, thdlam approved these changes

2024-08-06 15:07 UTC, merged