fix: update the character escape function in configuration service
GovAlta/adsp-monorepo pull request #3360
Opened 2024-08-28 22:33 UTC by solittlework

2024-08-29 22:23 UTC, tzuge requested changes

2024-08-29 22:46 UTC, solittlework commented on apps/configuration-service/src/mongo/repository.ts
> +        result.configuration = renamePrefixProperties(result.configuration, this.META_PREFIX, '$') as C;
Thanks, Ting. I've updated the related code.

2024-08-29 22:46 UTC, solittlework commented on apps/configuration-service/src/mongo/repository.ts
> +      configuration: renamePrefixProperties(doc.configuration, this.META_PREFIX, '$') as C,
Thanks, Ting. I've updated the related code.

2024-08-30 00:32 UTC, tzuge approved these changes

2024-08-30 14:08 UTC, merged